repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: name-tests-test
        args: ['--django']
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: double-quote-string-fixer
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.10
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.3
    hooks:
    -   id: reorder-python-imports
        language_version: python3.10
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    language_version: python3
